server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:AppointmentAppDB
    username: postgres
    password: root
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
